version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
install:
  - ps: mkdir -Force ".\build\" | Out-Null
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/serilog-*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: nvZ/z+pMS91b3kG4DgfES5AcmwwGoBYQxr9kp4XiJHj25SAlgdIxFx++1N0lFH2x
  skip_symbols: true
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifact: /serilog-*\.nupkg/
  on:
    branch: master
- provider: NuGet
  server: https://chocolatey.org/
  api_key:
    secure: 8hKKPtHptLzx2xq996Fxjq1oZ2HIOXJ6wpQlhPTrWjTC/jX4XXvNnSMAMC/XPoFK
  skip_symbols: true
  on:
    branch: master